version: 2

project_name: wormhole

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/wormhole
    binary: wormhole
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: MuhammadHananAsghar
      name: homebrew-tap
    homepage: "https://github.com/MuhammadHananAsghar/wormhole"
    description: "Expose your localhost to the internet. Open-source ngrok alternative."
    license: "MIT"
    install: |
      bin.install "wormhole"
    test: |
      system "#{bin}/wormhole", "version"

release:
  github:
    owner: MuhammadHananAsghar
    name: wormhole
